---

- name: Ensure PeerTube paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ peertube_uid }}"
    group: "{{ peertube_gid }}"
  with_items:
    - "{{ peertube_base_path }}"
    - "{{ peertube_config_dir_path }}"
    - "{{ peertube_data_dir_path }}"

- name: Ensure PeerTube support files created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ peertube_base_path }}/{{ item }}"
    owner: "{{ peertube_uid }}"
    group: "{{ peertube_gid }}"
    mode: 0640
  with_items:
    - env
    - labels

- name: Ensure PeerTube container network is created
  community.general.docker_network:
    name: "{{ peertube_container_network }}"
    driver: bridge

- name: Ensure PeerTube container image is pulled
  community.docker.docker_image:
    name: "{{ peertube_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ peertube_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else peertube_container_image_force_pull }}"

- name: Ensure PeerTube systemd service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/peertube.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ peertube_identifier }}.service"
    mode: 0644
