---

- name: Ensure PeerTube group is created
  ansible.builtin.group:
    name: "{{ peertube_playbook_user_groupname }}"
    gid: "{{ omit if peertube_playbook_gid is none else peertube_playbook_gid }}"
    state: present
  register: peertube_base_group_result

- name: Ensure PeerTube user is created
  ansible.builtin.user:
    name: "{{ peertube_playbook_user_username }}"
    uid: "{{ omit if peertube_playbook_uid is none else peertube_playbook_uid }}"
    state: present
    group: "{{ peertube_playbook_user_groupname }}"
    home: "{{ peertube_playbook_base_path }}"
    create_home: false
    system: true
  register: peertube_base_user_result

- name: Initialize peertube_playbook_uid and peertube_playbook_gid
  ansible.builtin.set_fact:
    peertube_playbook_uid: "{{ peertube_base_user_result.uid }}"
    peertube_playbook_gid: "{{ peertube_base_group_result.gid }}"
